name: Deploy-GCF-Send-Notifications

on:
  push:
    branches : main
    paths:
      - 'src/send_notifications/main.py'
      - 'src/send_notifications/requirements.txt'
      - '.github/workflows/deploy_send_notifications.yml'

jobs:
  deploy_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate in GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: Deploy the CF
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
            source_dir: src/send_notifications # name of directory
            name: send_notifications
            runtime: python37
            entry_point: main_func
            region: europe-west3
            timeout: 540
            max_instances: 1
            # memory_mb: 256
            event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
            event_trigger_resource: projects/lizaalert-bot-01/topics/topic_to_send_notifications
