name: Deploy-GCF-Check-First-Posts-For-Changes
env:
  FILE_NAME: check_first_posts_for_changes # UPD HERE!

on:
  push:
    branches : [main]
    paths:
      - 'check_first_posts_for_changes/main.py' # UPD HERE!
      - 'check_first_posts_for_changes/requirements.txt' # UPD HERE !
      - '.github/workflows/deploy_check_first_posts_for_changes.yml' # UPD HERE!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install anybadge
      - name: Saving the Score
        id: vars
        run: |
          python3 .pylint/lint.py;
          echo ::set-output name=score::"$(LINT_SCORE) 1"
      - name: Generating the badge
        run: |
          echo ${{ steps.vars.outputs.score }};
          anybadge -l pylint -v ${{ steps.vars.outputs.score }} -f .pylint/${{ env.FILE_NAME }}.svg 2=red 4=orange 8=yellow 10=green

  deploy_function:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.result == 'ne_success'

    steps:
      - uses: actions/checkout@v2

      - name: Authentificate in GCP
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: Deploy the CF
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0.6.0
        with:
            source_dir: ${{ env.FILE_NAME }} # name of directory
            name: ${{ env.FILE_NAME }} # name of deploying function
            runtime: python37
            entry_point: main # UPD HERE! main function
            region: europe-west3
            # timeout: 540 # UPD HERE!
            # max_instances: 1 # UPD HERE!
            # memory_mb: 8192 # UPD HERE!
            event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
            event_trigger_resource: projects/lizaalert-bot-01/topics/topic_for_update_every_N_minutes # UPD HERE! topic
