name: Deploy-GCF-Identify-Updates-Of-Topics

on:
  push:
    branches : main
    paths:
      - 'src/identify_updates_of_topics/main.py'
      - 'src/identify_updates_of_topics/requirements.txt'
      - '.github/workflows/deploy_identify_updates_of_topics.yml'

jobs:
  deploy_function:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate in GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.gcp_credentials }}

      - name: Deploy the CF
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
            source_dir: src/identify_updates_of_topics # name of directory
            name: identify_updates_of_topics
            runtime: python310
            entry_point: main
            region: europe-west3
            timeout: 540
            max_instances: 1
            memory_mb: 1024 # 2048
            event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
            event_trigger_resource: projects/lizaalert-bot-01/topics/topic_to_run_parsing_script
