name: Lint-Pull-Request

on:
  pull_request:
    branches : [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Get list of changed files
        id: changed_files
        run: |
          git diff --name-only origin/main...HEAD | grep '\.py$' > changed_files.txt
          cat changed_files.txt

      - name: Run Flake8 with Reviewdog on changed files
        if: success()
        run: |
          if [ -s changed_files.txt ]; then
            flake8 $(cat changed_files.txt) | reviewdog -f=flake8 -name="Flake8" -reporter=github-pr-review -level=error
          else
            echo "No Python files changed."
          fi
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: reviewdog/reviewdog@v0.12.0
        if: success()
        with:
          name: "Flake8"
          reporter: "github-pr-check"
          level: "warning"
