name: Lint-Pull-Request

on:
  pull_request:
    branches : [main, dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Flake8
        run: pip install flake8

      - name: Get list of changed files
        id: changed_files
        run: |
          git diff --name-only origin/main...HEAD | grep '\.py$' > changed_files.txt
          cat changed_files.txt

      - name: Run Flake8 with Reviewdog on changed files
        if: success() && steps.changed_files.outputs.changed_files != ''
        uses: reviewdog/action-flake8@v1
        with:
          tool_name: "flake8"
          reporter: "github-pr-review"
          level: "error"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
