name: Run-Tests

on:
  pull_request:
    branches: [main, dev]

permissions:
  pull-requests: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build containers and run tests
        run: |
          make ci-test
